Set module up at first

In [57]:
import numpy as np

initialize numpy array

In [58]:
a = np.array([[0, 1], [2, 3]])
a

array([[0, 1],
       [2, 3]])

dimention

In [59]:
a.ndim

2

array shape structure

In [60]:
a.shape

(2, 2)

Array size

In [61]:
a.size

4

Data type

In [62]:
a.dtype

dtype('int64')

In [63]:
a.data

# mathematical usage

In [64]:
b = np.array([[4, 5], [6, 7]])
b

array([[4, 5],
       [6, 7]])

In [65]:
np.add(a, b)

array([[ 4,  6],
       [ 8, 10]])

In [66]:
a + b

array([[ 4,  6],
       [ 8, 10]])

In [67]:
np.subtract(a, b)

array([[-4, -4],
       [-4, -4]])

In [68]:
a - b

array([[-4, -4],
       [-4, -4]])

In [69]:
np.multiply(a, b)

array([[ 0,  5],
       [12, 21]])

In [70]:
a * b

array([[ 0,  5],
       [12, 21]])

In [71]:
np.divide(a, b)

array([[0.        , 0.2       ],
       [0.33333333, 0.42857143]])

In [72]:
a / b

array([[0.        , 0.2       ],
       [0.33333333, 0.42857143]])

In [73]:
np.dot(a, b)

array([[ 6,  7],
       [26, 31]])

In [74]:
a.T

array([[0, 2],
       [1, 3]])

In [75]:
c = np.arange(10)
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
e = np.arange(3, 13).reshape(2, 5)
e

array([[ 3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12]])

In [77]:
d = c.reshape(2, 5)
d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [78]:
e * d

array([[  0,   4,  10,  18,  28],
       [ 40,  54,  70,  88, 108]])

# statistical usage

In [79]:
a

array([[0, 1],
       [2, 3]])

In [80]:
a.sum()

6

In [81]:
a.mean()

1.5

In [82]:
a.min()

0

In [83]:
a.max()

3

In [84]:
a.var()

1.25

In [85]:
a.std()

1.118033988749895

# Initialize usage

In [86]:
np.zeros(3)

array([0., 0., 0.])

In [87]:
np.zeros((2, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [88]:
np.zeros(10).reshape(5, 2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [89]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [90]:
np.ones((5, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [91]:
np.ones(10).reshape(2, 5)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [92]:
np.empty((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [93]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [94]:
np.random.random(25).reshape(5, 5)

array([[0.38714241, 0.76718423, 0.81174395, 0.31319072, 0.12735029],
       [0.64088487, 0.20800412, 0.96684693, 0.54099106, 0.99425277],
       [0.15403404, 0.04086684, 0.57833069, 0.49002731, 0.9889075 ],
       [0.07371555, 0.78083956, 0.98965407, 0.32255359, 0.60529976],
       [0.63556205, 0.52167106, 0.94411777, 0.63367218, 0.4111177 ]])

In [95]:
np.random.standard_normal(10)

array([ 0.48678695,  0.3357587 , -0.06468881,  0.63075954, -0.52263765,
       -0.12235152,  0.71974994,  0.42778379, -1.26329872,  0.95333961])

# Sortable

In [96]:
f = np.random.random(10)
f

array([0.94168578, 0.77158649, 0.07978176, 0.98899638, 0.25682946,
       0.2768004 , 0.57171832, 0.86977082, 0.79545285, 0.12047698])

In [97]:
np.sort(f)

array([0.07978176, 0.12047698, 0.25682946, 0.2768004 , 0.57171832,
       0.77158649, 0.79545285, 0.86977082, 0.94168578, 0.98899638])

In [98]:
arr = range(10)
np.array(arr).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [99]:
arr = range(10)
np.matrix(arr).reshape(2, 5)

matrix([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [100]:
np.linspace(0, 1, 100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [101]:
np.logspace(0, 1, 100, base=10)

array([ 1.        ,  1.02353102,  1.04761575,  1.07226722,  1.09749877,
        1.12332403,  1.149757  ,  1.17681195,  1.20450354,  1.23284674,
        1.26185688,  1.29154967,  1.32194115,  1.35304777,  1.38488637,
        1.41747416,  1.45082878,  1.48496826,  1.51991108,  1.55567614,
        1.59228279,  1.62975083,  1.66810054,  1.70735265,  1.7475284 ,
        1.78864953,  1.83073828,  1.87381742,  1.91791026,  1.96304065,
        2.009233  ,  2.05651231,  2.10490414,  2.15443469,  2.20513074,
        2.25701972,  2.3101297 ,  2.36448941,  2.42012826,  2.47707636,
        2.53536449,  2.59502421,  2.65608778,  2.71858824,  2.7825594 ,
        2.84803587,  2.91505306,  2.98364724,  3.05385551,  3.12571585,
        3.19926714,  3.27454916,  3.35160265,  3.43046929,  3.51119173,
        3.59381366,  3.67837977,  3.76493581,  3.85352859,  3.94420606,
        4.03701726,  4.1320124 ,  4.22924287,  4.32876128,  4.43062146,
        4.53487851,  4.64158883,  4.75081016,  4.86260158,  4.97

In [102]:
np.zeros((5, 5, 5)).astype(int) + 1

array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]])

In [103]:
np.ones((5, 5, 5)).astype(np.float16)

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float16)

In [104]:
np.linspace(0, 10, 100).astype(int)

array([ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  3,  3,  3,  3,
        3,  3,  3,  3,  3,  3,  4,  4,  4,  4,  4,  4,  4,  4,  4,  4,  5,
        5,  5,  5,  5,  5,  5,  5,  5,  5,  6,  6,  6,  6,  6,  6,  6,  6,
        6,  6,  7,  7,  7,  7,  7,  7,  7,  7,  7,  7,  8,  8,  8,  8,  8,
        8,  8,  8,  8,  8,  9,  9,  9,  9,  9,  9,  9,  9,  9, 10])

# Slice array contents

In [105]:
a = np.arange(100)
print(a)
print(a[10])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
10


In [106]:
a = np.arange(25).reshape(5, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [107]:
print(a[3, 2])

17


In [108]:
print(a[2:])

[[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [109]:
print(a[:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [110]:
a[2,:]

array([10, 11, 12, 13, 14])

In [111]:
a[:,2]

array([ 2,  7, 12, 17, 22])